= Managing Connections
:description: This section describes how to connect the {name-sdk} to an Analytics cluster.
:page-toclevels: 2


// Note to editors
// 
// This page pulls in content from -sdk-common-
// and code samples from -example-dir-
// 
// It can be seen built at wwww.


[abstract]
{description}
It contains best practices as well as information on TLS/SSL and advanced connection options, and a sub-page on troubleshooting remote connections during devlopment.


Our xref:hello-world:start-using-sdk.adoc[Getting Started pages] cover the basics of making a connection to an Enterprise Analytics cluster.
// (Capella or self-managed).
This page is a wider look at the topic.


== Connecting to a Cluster

The examples below use these imports:

[source,csharp]
----
using Couchbase.AnalyticsClient;
using Couchbase.AnalyticsClient.HTTP;
using Couchbase.AnalyticsClient.Options;
----

A connection to an Enterprise Analytics cluster is represented by a `Cluster` object.
A `Cluster` provides access to databases, scopes, and collections, as well as various Analytics services and management interfaces.
The simplest way to create a `Cluster` object is to call `Cluster.Create()` with a <<connection-strings, connection string>>, username, and password:

[source,csharp]
----
var credential = Credential.Create("username", "password");

var cluster = Cluster.Create(
    connectionString: "https://analytics.my-couchbase.example.com:18095",
    credential: credential);
----

NOTE: Capella's root certificate is *not* signed by a well known Certificate Authority.
However, the certificate is bundled with the SDK, and is automatically trusted unless you specify a different certificate to trust.

== Connection Strings


include::{version-common}@analytics-sdk:shared:partial$connstr.adoc[tag=more-connstr]



.Connection string with two parameters
----
http://localhost:8095?timeout.connect_timeout=30s&timeout.query_timeout=2m
----

The full list of recognized parameters is documented in the xref:ref:client-settings.adoc[client settings reference].



== Local Development


We strongly recommend that the client and server xref:project-docs:compatibility.adoc#network-requirements[are in the same LAN-like environment] (for example, the same AWS Region).
// As this may not always be possible during development, read the guidance on working with xref:ref:client-settings.adoc#commonly-used-options[constrained network environments].