= Managing Connections
:description: This section describes how to connect the {name-sdk} to an Analytics cluster.
:page-toclevels: 2


// Note to editors
// 
// This page pulls in content from -sdk-common-
// and code samples from -example-dir-
// 
// It can be seen built at wwww.


[abstract]
{description}
It contains best practices as well as information on TLS/SSL and advanced connection options, and a sub-page on troubleshooting remote connections during devlopment.


Our xref:hello-world:start-using-sdk.adoc[Getting Started pages] cover the basics of making a connection to an Enterprise Analytics cluster.
// (Capella or self-managed).
This page is a wider look at the topic.


== Connecting to a Cluster

The examples below use these imports:

[source,csharp]
----
using Couchbase.AnalyticsClient;
using Couchbase.AnalyticsClient.HTTP;
using Couchbase.AnalyticsClient.Options;
----

A connection to an Enterprise Analytics cluster is represented by a `Cluster` object.
A `Cluster` provides access to databases, scopes, and collections, as well as various Analytics services and management interfaces.
The simplest way to create a `Cluster` object is to call `Cluster.Create()` with a <<connection-strings, connection string>>, username, and password:

[source,csharp]
----
var credential = Credential.Create("username", "password");
public static Cluster Create(string connectionString, ICredential credential);
----


== Connection Strings


include::{version-common}@analytics-sdk:shared:partial$connstr.adoc[tag=more-connstr]



== Authentication by Credential

Similarly to the `Authenticator` abstraction in Couchbase Operational SDKs, Analytics SDKs use a `Credential` abstraction covering regular password authentication (Basic Access Authentication), JSON Web Tokens (JWT), and Client Certificates through mTLS.

Basic Access Authentication is shown in the example <<#connecting-to-a-cluster,above>>.


=== JSON Web Tokens (JWT)

From the 1.1 SDK (with Enterprise Analytics Server 2.2+) JWT is supported.

[source,csharp]
----
var credential = JwtCredential.Create(token);
public static Cluster Create(string connectionString, ICredential credential);
----


=== Certificate Authentication

From the 1.1 Analytics SDK (with Enterprise Analytics Server 2.2+) certificate authentication is supported.
A conceptual and architectural overview of Enterprise Analytics's support of X.509 certificates is provided in the xref:{version-server}@server:learn:security/certificates.adoc[Server certificates docs].
Practical information on handling certificates can be found in the xref:{version-ea}@enterprise-analytics:manage:manage-security/manage-certificates.adoc[Enterprise Analytics certificates docs].

The Analytics SDK authenticates the client during the TLS handshake.
The SDK reads the certificate and private key from a `PKCS#12` file:

[source,csharp]
----
var credential = CertificateCredential.FromPem(certPath, keyPath);
public static Cluster Create(string connectionString, ICredential credential);
----


== Certificate Authority

To make a TLS connection to an Enterprise Analytics cluster with a root certificate issued by a trusted CA (Certificate Authority), you do not need to add this to your configuration --
the platform's defaults are automatically trusted.

The cluster's root certificate just needs to be issued by a CA whose certificate is in your system trust store.
This includes well known CAs (including GoDaddy and Verisign), plus any other CA certificates that you wish to add.


== Local Development

We strongly recommend that the client and server xref:project-docs:compatibility.adoc#network-requirements[are in the same LAN-like environment] (for example, the same AWS Region).
// As this may not always be possible during development, read the guidance on working with xref:ref:client-settings.adoc#commonly-used-options[constrained network environments].
