= Analytics SDK Release Notes
:description: Release notes, brief installation instructions, and download archive for the Enterprise Analytics .NET Client.
:navtitle: Release Notes
:page-toclevels: 2
:page-aliases: sdk-release-notes.adoc

// tag::all[]
[abstract]
{description}

Version {sdk_dot_minor} of the .NET Analytics SDK implements the {sdk_api} xref:compatibility.adoc#api-version[SDK API].
See the xref:compatibility.html#couchbase-feature-availability-matrix[compatibility pages] for more information on feature compatibility with different versions of Enterprise Analytics.


== Installation

See the xref:project-docs:sdk-full-installation.adoc[Installation] guide for details.

// tag::all[]


[#latest-release]
== .NET Analytics SDK 1.0 Releases

We always recommend using the latest version of the SDK -- it contains all of the latest security patches and support for new and upcoming features.
All patch releases for each dot minor release should be API compatible, and safe to upgrade;
any changes to expected behavior are noted in the release notes that follow.


=== Version 1.0.0 (7 October 2025)

https://docs.couchbase.com/sdk-api/analytics-dotnet-client-1.0.0[API Reference]

This is the first General Availability (GA) release of the new Analytics .NET SDK. 
It supports executing queries against Enterprise Analytics clusters, with additional features planned for future releases.
// end::all[]
